basket/urls.py
from django.urls import path
from basket.views import basket_add, basket_remove, basket_edit

app_name='basket'

urlpatterns = [
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-remove/<int:id>', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp_views
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basket.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admins')),
    path('',include('social_django.urls', namespace = 'social')),
    path('order/', include('orderapp.urls', namespace='orders')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orderapp/urls.py
from django.urls import path, re_path
from orderapp import views
from django.views.decorators.cache import cache_page


app_name='orderapp'

urlpatterns = [
    path('', cache_page(20)(views.OrderList.as_view()), name='order_list'),
    path('create/', views.OrderItemsCreate.as_view(), name='order_create'),
    path('update/<int:pk>/', views.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', views.OrderDelete.as_view(), name='order_delete'),
    path('detail/<int:pk>/', views.OrderRead.as_view(), name='order_detail'),
    path('forming/complete/<int:pk>/', views.order_forming_complete, name='order_complete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', views.get_product_price),
]

orderapp/models.py
from django.db import models
from django.db.models import F

from authapp.models import User
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOISES = (
        (FORMING,'формируется'),
        (SENT_TO_PROCEED,'отправлен в обработку'),
        (PROCEED,'обрабатывается'),
        (PAID,'оплачен'),
        (READY,'готов к выдаче'),
        (CANCEL,'отменен'),
    )

    user = models.ForeignKey(User,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=3, verbose_name='статус',choices=ORDER_STATUS_CHOISES,default=FORMING)
    is_active = models.BooleanField(default=True, verbose_name='активен')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f' Заказ: {self.id}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))


    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity*x.product.price, items)))

    def get_total_type_quantity(self):
        return len(self.orderitems.select_related())

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity = F('quantity') + item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.IntegerField(default=0,verbose_name='количество')

    def get_product_cost(self):
        return self.quantity * self.product.price

orderapp/forms.py
from orderapp.models import Order, OrderItem
from django import forms


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args,**kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='Цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

orderapp/views.py
from django.shortcuts import get_object_or_404,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.http import JsonResponse
from django.views.decorators.cache import cache_page

from mainapp.models import Product
from .models import Order, OrderItem
from .forms import OrderItemForm
from basket.models import Basket
from django.forms import inlineformset_factory
from django.db.transaction import atomic


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orderapp:order_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with atomic():
            Basket.objects.filter(user=self.request.user).delete()
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orderapp:order_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order,OrderItem,form=OrderItemForm, extra=1)

        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
            data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('orderapp:order_list')

class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просморт'
        return context


def order_forming_complete(request,pk):
    order = get_object_or_404(Order,pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('orderapp:order_list'))


@cache_page(120)
def get_product_price(request,pk):
    if request.is_ajax():
        product = Product.objects.filter(pk = int(pk)).first()
        if product:
            return JsonResponse({'price':product.price})
        else:
            return JsonResponse({'price': 0})

orderapp/templates/orderapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/order_detail.css' %}" rel="stylesheet">

</head>
<body>

<h2>This is base template </h2>
{% block content %}

{% endblock %}
</body>
</html>

orderapp/templates/orderapp/order_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block content %}
   <div class="category_delete container">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'orderapp/includes/inc_order_summary.html' %}
       <form action="{% url 'orderapp:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'orderapp:order_list' %}">отмена</a>
       </button>
   </div>
{% endblock %}

orderapp/templates/orderapp/order_detail.html
{% extends "mainapp/base.html" %}
{% load staticfiles %}
{#{% load my_tags %}#}

{% block content %}
    <div class="container">
        {% include 'orderapp/includes/inc_order_summary.html' %}
        <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img class="card_ord" style="width: 100px" src="/media/{{item.product.image}}"
                    alt="" >
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
        {% include 'orderapp/includes/inc_order_actions.html' %}
    </div>


{% endblock %}

orderapp/templates/orderapp/order_form.html
{% extends "mainapp/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
    <div style="height: 100px"></div>
   <div class="container">
        {% include 'orderapp/includes/inc_order_summary.html' %}
        <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                               {% if field.name != 'price' %}
                                   {% if field.name == 'product' %}
                                       {% cache 3600 orderitemform_product field.value %}
                                           {{ field }}
                                       {% endcache %}
                                   {% else %}
                                       {{ field }}
                                   {% endif %}

                               {% else %}
                                {% if field.value %}
                                    <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                        {{ field.value }}
                                    </span> руб
                                {% endif %}
                               {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
           {% include 'orderapp/includes/inc_order_actions.html' %}
       </form>
   </div>
   </div>


{% endblock %}

orderapp/templates/orderapp/order_list.html
{% extends 'mainapp/base.html' %}

{% block content %}

    <div class="container" style="padding-top: 56px">

        <div class="row">
            <div class="col-lg-9">
                <h3 class="my-5">Заказы пользователя {{ user.first_name }}</h3>
                <div class="col-8">
                    <table class="table table-striped">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Статус</th>
            <th scope="col">Посмотреть</th>
            <th scope="col">Обновить</th>
            <th scope="col">Удалить</th>
        </tr>
        {% for item in object_list %}
            {% if item.is_active %}
            <tr>
            <th scope="row">{{ item.id }}</th>
            <td>{{ item.get_status_display }}</td>
            <td><a href="{% url 'orderapp:order_detail' item.id %}">Ссылка</a></td>
            <td><a href="{% url 'orderapp:order_update' item.id %}">Редактировать</a></td>
            <td><a href="{% url 'orderapp:order_delete' item.id %}">Удалить</a></td>
            </tr>
            {% endif %}
        {% endfor %}

    </table>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}